FROM golang:1.24-alpine

# 更换apk源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
# 设置工作目录
WORKDIR /app
# 设置源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# 安装必要的工具
RUN apk add --no-cache git ca-certificates tzdata wget

# 安装 Air 热更新工具
RUN go env -w GOPROXY=https://goproxy.cn,direct

RUN go install github.com/air-verse/air@v1.60.0

# 复制 go mod 文件
COPY go.mod go.sum ./

# 下载依赖
RUN go mod download

# 复制源代码
COPY . .

# 创建必要的目录
RUN mkdir -p /app/logs

# 暴露端口
EXPOSE 8080

# 使用 Air 启动应用 (热更新)
CMD ["air", "-c", ".air.toml"]
